instance: "secure1"
env: "local"
use_kafka: true
http_server:
  address: "localhost:8159"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s
  shutdown_timeout: 15s
  request_timeout: 50s
persistent_storage:
  database_login: "lex"
  database_password: "python"
  database_address: "192.168.31.224"
  database_port: 5432
  database_max_open_connections: 10
  database_name: "secure1"
  query_timeout: 5s
kafka:
  kafka_brokers: ["localhost:9092"]
  kafka_topic_need_update_token: "secure.update-token"
  kafka_number_of_retries_to_send_message: 2
  kafka_time_between_attempts: 250ms
  kafka_write_timeout: 10s
redis:
  redis_address: "127.0.0.0:6379"
  redis_user: ""
  redis_password: ""
  redis_db: 0
ttl:
  session_ttl: 24h
  user_id_and_password_hash_ttl: 168h
  account_state_ttl: 168h
  permissions_numbers_ttl: 24h
  instance_data_ttl: 168h
secure:
  login_token_length: 24
  password_creation_cost: 14
  token_ttl: 168h