// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricsInterface is a mock of MetricsInterface interface.
type MockMetricsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsInterfaceMockRecorder
}

// MockMetricsInterfaceMockRecorder is the mock recorder for MockMetricsInterface.
type MockMetricsInterfaceMockRecorder struct {
	mock *MockMetricsInterface
}

// NewMockMetricsInterface creates a new mock instance.
func NewMockMetricsInterface(ctrl *gomock.Controller) *MockMetricsInterface {
	mock := &MockMetricsInterface{ctrl: ctrl}
	mock.recorder = &MockMetricsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsInterface) EXPECT() *MockMetricsInterfaceMockRecorder {
	return m.recorder
}

// AuthenticationErrorInc mocks base method.
func (m *MockMetricsInterface) AuthenticationErrorInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AuthenticationErrorInc")
}

// AuthenticationErrorInc indicates an expected call of AuthenticationErrorInc.
func (mr *MockMetricsInterfaceMockRecorder) AuthenticationErrorInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticationErrorInc", reflect.TypeOf((*MockMetricsInterface)(nil).AuthenticationErrorInc))
}

// LoginInc mocks base method.
func (m *MockMetricsInterface) LoginInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LoginInc")
}

// LoginInc indicates an expected call of LoginInc.
func (mr *MockMetricsInterfaceMockRecorder) LoginInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginInc", reflect.TypeOf((*MockMetricsInterface)(nil).LoginInc))
}
